apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-volume ## Persitent Volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /shares/registry ## NFS path 
    server: nfs.openshift.example.com ## NFS server name
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: registry-pvclaim ## Claim Name
    namespace: default ## Project name
